name: RBWBot
main: com.deyo.rbw.ingame.Main
version: 1.0
author: Dreamrela
description: Ranked BedWars Discord/Bukkit Integration
commands:
  link:
    description: Main command for Ranked BedWars
    usage: /rbw
  guild:
    description: Guild system command
    usage: /guild
